"""
Acquisitions phrase bank — real operator speech patterns, not AI completions.

Used by SpokenRendererProcessor to replace high-AI-score outputs.
All phrases drawn from real acquisitions call patterns.
"""

# Allowed acknowledgement bank — tiny on purpose
# These must be SELECTED by the renderer, not generated by LLM
ACK_BANK = [
    "Okay.",
    "Gotcha.",
    "Alright.",
    "Makes sense.",
    "I hear you.",
    "Yeah.",
    "Right.",
    "Okay, yeah.",
    "Got it.",
]

# Per-objective qualification pivots
# Renderer picks one after an ack when pacing is operational/tight
PIVOT_BANK: dict[str, list[str]] = {
    "CONFIRM_INTENT": [
        "You looking to sell it, or just seeing what it might be worth?",
        "Were you thinking about selling, or not really?",
        "You interested in selling, or just curious?",
    ],
    "GET_ADDRESS": [
        "What's the address on that?",
        "And the address?",
        "What property are we talking about?",
    ],
    "GET_MOTIVATION": [
        "What's the situation with it?",
        "What's going on with it?",
        "What's got you thinking about selling?",
    ],
    "GET_OCCUPANCY": [
        "Vacant right now, or someone living there?",
        "Anyone living there currently?",
        "Is it vacant, or you got a tenant in there?",
    ],
    "GET_CONDITION": [
        "Does it need work, or is it pretty solid?",
        "What kind of shape is it in?",
        "Updated, or does it need some work?",
    ],
    "GET_TIMELINE": [
        "How soon are you looking to move on this?",
        "What's your timeline like?",
        "How fast do you need to be done?",
    ],
    "TEST_PRICE": [
        "What do you need to walk away with?",
        "What's your number?",
        "What would make this work for you?",
    ],
    "BOOK_APPOINTMENT": [
        "Tomorrow afternoon or the next morning — which works?",
        "What does your schedule look like this week?",
        "I could have someone out this week. Which day's easier?",
    ],
}

# Redirect phrases for rambling sellers
REDIRECT_BANK: list[str] = [
    "Got it. And the property?",
    "Makes sense. What's the situation with the house?",
    "Okay. How soon are you looking to move?",
    "Sure. What's the address on that?",
]

# Pushback phrases by context
PUSHBACK_BANK: dict[str, list[str]] = {
    "price_too_high": [
        "Why not list it?",
        "That's pretty strong. Why not go with an agent?",
        "We might not be the right fit then.",
    ],
    "price_demand": [
        "How'd you land on that number?",
        "Okay… where's that coming from?",
        "What makes you think it's worth that?",
    ],
    "just_browsing": [
        "Okay. Are you serious about selling, or just seeing what's out there?",
        "Gotcha. So you're not really in a hurry?",
    ],
    "needs_info_first": [
        "Usually helps if I understand the property first.",
        "I can try, but I'd need to know the condition first.",
        "Gotcha. I'd just need a couple quick questions about it.",
    ],
    "not_interested": [
        "Totally. Before I let you go — never sell, or just not unless the number was strong?",
        "No problem. Would you ever consider it, or no?",
    ],
}
