ALTER TABLE leads ADD COLUMN IF NOT EXISTS speed_to_lead_attempts integer DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS speed_to_lead_completed boolean DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS motivation_level integer;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS price_floor bigint;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS timeline_urgency text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS hot_topics jsonb DEFAULT '[]';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS rapport_openers jsonb DEFAULT '[]';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS competitor_mentions jsonb DEFAULT '[]';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_best_action text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS call_summary text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email_day integer DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email_paused boolean DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email_completed boolean DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_email_at timestamptz;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS composite_score float;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS recency_score integer DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS intensity_score integer DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS pattern_score integer DEFAULT 0;
ALTER TABLE calls ADD COLUMN IF NOT EXISTS callback_from_voicemail boolean DEFAULT false;
ALTER TABLE calls ADD COLUMN IF NOT EXISTS voicemail_script integer;
